apiVersion: apps/v1
kind: Deployment
metadata:
  name: picrunch
spec:
  selector:
    matchLabels:
      app: picrunch
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: picrunch
    spec:
      containers:
      - name: picrunch
        image: jelaiw/picrunch:0.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: picrunch
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: picrunch
